//
//  PasteBoard.swift
//  Clipboard
//
//  Created by crown on 2025/9/13.
//

import AppKit
import Foundation

final class PasteBoard {
    static let main = PasteBoard()

    private let pasteboard = NSPasteboard.general
    private let timerInterval = 0.5
    private var changeCount: Int
    private var pasteModel: PasteboardModel?
    private var timer: Timer?

    // MARK: - 暂停功能

    private(set) var isPaused: Bool = false
    private(set) var pausedAt: Date?
    /// 暂停持续时长（秒），nil 表示无限期
    private var pauseDuration: TimeInterval?
    private var resumeTimer: Timer?

    private static let sensitiveTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "com.apple.password",
        "com.apple.securetext",
        "com.agilebits.onepassword", // 1Password
        "com.lastpass.mac", // LastPass
        "com.dashlane.dashlanephonefinal", // Dashlane
        "com.keeper.KeeperPassManager", // Keeper
        "io.enpass.Enpass", // Enpass
        "com.bitwarden.desktop", // Bitwarden
    ]

    private static let ephemeralTypes: Set<String> = [
        "org.nspasteboard.TransientType", // 瞬时内容标准标识
        "org.nspasteboard.AutoGeneratedType", // 自动生成内容
        "org.nspasteboard.RestoredType", // 恢复的内容
        "de.petermaurer.TransientPasteboardType", // TextExpander/Butler
        "com.typeit4me.clipping", // TypeIt4Me
        "com.apple.pasteboard.promised-file-content-type",
    ]

    init() {
        changeCount = pasteboard.changeCount
    }

    func startListening() {
        stopListening()

        timer = Timer.scheduledTimer(
            timeInterval: timerInterval,
            target: self,
            selector: #selector(checkForChangesInPasteboard),
            userInfo: nil,
            repeats: true
        )
        RunLoop.main.add(timer!, forMode: .common)
    }

    func stopListening() {
        timer?.invalidate()
        timer = nil
    }

    // MARK: - 暂停/恢复

    /// - Parameter duration: 暂停时长（秒），nil 表示无限期暂停
    func pause(for duration: TimeInterval? = nil) {
        if isPaused {
            resumeTimer?.invalidate()
            resumeTimer = nil
        } else {
            stopListening()
        }

        isPaused = true
        pausedAt = Date()
        pauseDuration = duration

        if let duration {
            resumeTimer = Timer.scheduledTimer(
                withTimeInterval: duration,
                repeats: false
            ) { [weak self] _ in
                Task { @MainActor in
                    self?.resume()
                }
            }
            RunLoop.main.add(resumeTimer!, forMode: .common)
        }

        NotificationCenter.default.post(name: .pasteboardPauseStateChanged, object: nil)
    }

    func resume() {
        guard isPaused else { return }

        resumeTimer?.invalidate()
        resumeTimer = nil

        isPaused = false
        pausedAt = nil
        pauseDuration = nil
        startListening()

        NotificationCenter.default.post(name: .pasteboardPauseStateChanged, object: nil)
    }

    /// 剩余暂停时间（秒）
    var remainingPauseTime: TimeInterval? {
        guard isPaused, let pausedAt, let pauseDuration else {
            return nil
        }
        let elapsed = Date().timeIntervalSince(pausedAt)
        return max(0, pauseDuration - elapsed)
    }

    var pauseEndTime: Date? {
        guard isPaused, let pausedAt, let pauseDuration else {
            return nil
        }
        return pausedAt.addingTimeInterval(pauseDuration)
    }

    /// 是否为无限期暂停
    var isIndefinitePause: Bool {
        isPaused && pauseDuration == nil
    }

    @objc private func checkForChangesInPasteboard() {
        guard pasteboard.changeCount != changeCount else {
            return
        }

        if pasteModel != nil {
            changeCount = pasteboard.changeCount
            pasteModel = nil
            return
        }

        let types = pasteboard.types ?? []

        // 检查隐私设置：忽略机密内容和瞬时内容
        let checkSensitive = PasteUserDefaults.ignoreSensitiveContent
        let checkEphemeral = PasteUserDefaults.ignoreEphemeralContent

        if checkSensitive || checkEphemeral {
            let ignoreResult = shouldIgnoreContent(
                types: types,
                checkSensitive: checkSensitive,
                checkEphemeral: checkEphemeral
            )
            if let reason = ignoreResult {
                log.info("检测到需忽略的内容，跳过记录: \(reason)")
                changeCount = pasteboard.changeCount
                return
            }
        }

        // 检查隐私设置：忽略特定应用
        let ignoredApps = PasteUserDefaults.ignoredApps
        if !ignoredApps.isEmpty, let sourceApp = getSourceApplication() {
            let shouldIgnore = ignoredApps.contains { app in
                if let bundleId = app.bundleIdentifier,
                   bundleId == sourceApp.bundleIdentifier
                {
                    return true
                }
                return app.path == sourceApp.bundleURL?.path
            }

            if shouldIgnore {
                log.info(
                    "来自忽略应用的内容，跳过记录: \(sourceApp.localizedName ?? "Unknown")"
                )
                changeCount = pasteboard.changeCount
                return
            }
        }

        #if DEBUG
            guard let item = pasteboard.pasteboardItems?.first else { return }
            let debugTypes = item.types.map(\.rawValue)
            log.debug("可用类型 \(debugTypes)")
        #endif

        PasteDataStore.main.addNewItem(pasteboard)
        changeCount = pasteboard.changeCount

        AppDelegate.shared?.triggerStatusBarPulse()
        SoundManager.shared.play(.copy)
    }

    /// 检查敏感内容和瞬时内容
    private func shouldIgnoreContent(
        types: [NSPasteboard.PasteboardType],
        checkSensitive: Bool,
        checkEphemeral: Bool
    ) -> String? {
        for type in types {
            let rawType = type.rawValue
            if checkSensitive, Self.sensitiveTypes.contains(rawType) {
                return "机密内容: \(rawType)"
            }
            if checkEphemeral, Self.ephemeralTypes.contains(rawType) {
                return "瞬时内容: \(rawType)"
            }
        }
        return nil
    }

    private func getSourceApplication() -> NSRunningApplication? {
        NSWorkspace.shared.frontmostApplication
    }

    func pasteData(_ data: PasteboardModel, _ isAttribute: Bool = true) {
        data.updateDate()
        pasteModel = data
        if let itemId = data.id {
            PasteDataStore.main.updateDbItem(id: itemId, item: data)
        }
        NSPasteboard.general.clearContents()

        let success = writeToPasteboard(data, isAttribute: isAttribute)
        guard success else { return }

        PasteDataStore.main.moveItemToFirst(data)
        SoundManager.shared.play(.paste)
    }

    /// 将数据写入系统剪贴板
    /// - Returns: 是否成功写入
    private func writeToPasteboard(_ data: PasteboardModel, isAttribute: Bool) -> Bool {
        let shouldPasteAsPlainText = !isAttribute || PasteUserDefaults.pasteOnlyText

        switch data.type {
        case .string where shouldPasteAsPlainText, .rich where shouldPasteAsPlainText:
            writePlainText(data)
            return true

        case .file:
            return writeFileURLs(data)

        default:
            writeRawData(data)
            return true
        }
    }

    /// 写入纯文本
    private func writePlainText(_ data: PasteboardModel) {
        var text = data.searchText
        if PasteUserDefaults.removeTailingNewline {
            text = text.trimmingTrailingNewlines()
        }
        NSPasteboard.general.setString(text, forType: .string)
    }

    /// 写入文件 URL
    /// - Returns: 是否有有效文件写入
    private func writeFileURLs(_ data: PasteboardModel) -> Bool {
        guard let filePaths = String(data: data.data, encoding: .utf8) else {
            return false
        }

        let fileManager = FileManager.default
        let validURLs = filePaths
            .components(separatedBy: "\n")
            .lazy
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty && fileManager.fileExists(atPath: $0) }
            .map { URL(fileURLWithPath: $0) }

        let urlArray = Array(validURLs)
        guard !urlArray.isEmpty else { return false }

        pasteboard.writeObjects(urlArray as [NSPasteboardWriting])
        return true
    }

    /// 写入原始数据（富文本、图片等）
    private func writeRawData(_ data: PasteboardModel) {
        // 处理需要去除末尾换行的富文本
        if data.pasteboardType.isText(),
           PasteUserDefaults.removeTailingNewline,
           let attributedString = NSAttributedString(with: data.data, type: data.pasteboardType)
        {
            let mutableString = NSMutableAttributedString(attributedString: attributedString)
            mutableString.trimTrailingNewlines()

            if let processedData = mutableString.toData(with: data.pasteboardType) {
                NSPasteboard.general.setData(processedData, forType: data.pasteboardType)
                return
            }
        }

        NSPasteboard.general.setData(data.data, forType: data.pasteboardType)
    }
}

// MARK: - NSMutableAttributedString Extension

private extension NSMutableAttributedString {
    func trimTrailingNewlines() {
        var currentLength = length
        while currentLength > 0 {
            let lastCharRange = NSRange(location: currentLength - 1, length: 1)
            let lastChar = attributedSubstring(from: lastCharRange).string

            if lastChar == "\n" || lastChar == "\r" {
                currentLength -= 1
            } else {
                break
            }
        }

        if currentLength < length {
            deleteCharacters(in: NSRange(location: currentLength, length: length - currentLength))
        }
    }
}

// MARK: - Notification

extension Notification.Name {
    static let pasteboardPauseStateChanged = Notification.Name("pasteboardPauseStateChanged")
}
