//
//  PasteBoard.swift
//  Clipboard
//
//  Created by crown on 2025/9/13.
//

import AppKit
import Foundation

final class PasteBoard {
    static let main = PasteBoard()

    private let pasteboard = NSPasteboard.general
    private let timerInterval = 0.5
    private var changeCount: Int
    private var pasteModel: PasteboardModel?
    private var timer: Timer?

    // MARK: - 暂停功能

    private(set) var isPaused: Bool = false
    private(set) var pausedAt: Date?
    /// 暂停持续时长（秒），nil 表示无限期
    private var pauseDuration: TimeInterval?
    private var resumeTimer: Timer?

    private static let sensitiveTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "com.apple.password",
        "com.apple.securetext",
        "com.agilebits.onepassword", // 1Password
        "com.lastpass.mac", // LastPass
        "com.dashlane.dashlanephonefinal", // Dashlane
        "com.keeper.KeeperPassManager", // Keeper
        "io.enpass.Enpass", // Enpass
        "com.bitwarden.desktop", // Bitwarden
    ]

    private static let ephemeralTypes: Set<String> = [
        "org.nspasteboard.TransientType", // 瞬时内容标准标识
        "org.nspasteboard.AutoGeneratedType", // 自动生成内容
        "org.nspasteboard.RestoredType", // 恢复的内容
        "de.petermaurer.TransientPasteboardType", // TextExpander/Butler
        "com.typeit4me.clipping", // TypeIt4Me
        "com.apple.pasteboard.promised-file-content-type",
    ]

    init() {
        changeCount = pasteboard.changeCount
    }

    func startListening() {
        stopListening()

        timer = Timer.scheduledTimer(
            timeInterval: timerInterval,
            target: self,
            selector: #selector(checkForChangesInPasteboard),
            userInfo: nil,
            repeats: true
        )
        RunLoop.main.add(timer!, forMode: .common)
    }

    func stopListening() {
        timer?.invalidate()
        timer = nil
    }

    // MARK: - 暂停/恢复

    /// - Parameter duration: 暂停时长（秒），nil 表示无限期暂停
    func pause(for duration: TimeInterval? = nil) {
        if isPaused {
            resumeTimer?.invalidate()
            resumeTimer = nil
        } else {
            stopListening()
        }

        isPaused = true
        pausedAt = Date()
        pauseDuration = duration

        if let duration {
            resumeTimer = Timer.scheduledTimer(
                withTimeInterval: duration,
                repeats: false
            ) { [weak self] _ in
                Task { @MainActor in
                    self?.resume()
                }
            }
            RunLoop.main.add(resumeTimer!, forMode: .common)
        }

        NotificationCenter.default.post(name: .pasteboardPauseStateChanged, object: nil)
    }

    func resume() {
        guard isPaused else { return }

        resumeTimer?.invalidate()
        resumeTimer = nil

        isPaused = false
        pausedAt = nil
        pauseDuration = nil
        startListening()

        NotificationCenter.default.post(name: .pasteboardPauseStateChanged, object: nil)
    }

    /// 剩余暂停时间（秒）
    var remainingPauseTime: TimeInterval? {
        guard isPaused, let pausedAt, let pauseDuration else {
            return nil
        }
        let elapsed = Date().timeIntervalSince(pausedAt)
        return max(0, pauseDuration - elapsed)
    }

    var pauseEndTime: Date? {
        guard isPaused, let pausedAt, let pauseDuration else {
            return nil
        }
        return pausedAt.addingTimeInterval(pauseDuration)
    }

    /// 是否为无限期暂停
    var isIndefinitePause: Bool {
        isPaused && pauseDuration == nil
    }

    @objc private func checkForChangesInPasteboard() {
        guard pasteboard.changeCount != changeCount else {
            return
        }

        if pasteModel != nil {
            changeCount = pasteboard.changeCount
            pasteModel = nil
            return
        }

        let types = pasteboard.types ?? []

        // 检查隐私设置：忽略机密内容和瞬时内容
        let checkSensitive = PasteUserDefaults.ignoreSensitiveContent
        let checkEphemeral = PasteUserDefaults.ignoreEphemeralContent

        if checkSensitive || checkEphemeral {
            let ignoreResult = shouldIgnoreContent(
                types: types,
                checkSensitive: checkSensitive,
                checkEphemeral: checkEphemeral
            )
            if let reason = ignoreResult {
                log.info("检测到需忽略的内容，跳过记录: \(reason)")
                changeCount = pasteboard.changeCount
                return
            }
        }

        // 检查隐私设置：忽略特定应用
        let ignoredApps = PasteUserDefaults.ignoredApps
        if !ignoredApps.isEmpty, let sourceApp = getSourceApplication() {
            let shouldIgnore = ignoredApps.contains { app in
                if let bundleId = app.bundleIdentifier,
                   bundleId == sourceApp.bundleIdentifier
                {
                    return true
                }
                return app.path == sourceApp.bundleURL?.path
            }

            if shouldIgnore {
                log.info(
                    "来自忽略应用的内容，跳过记录: \(sourceApp.localizedName ?? "Unknown")"
                )
                changeCount = pasteboard.changeCount
                return
            }
        }

        #if DEBUG
            guard let item = pasteboard.pasteboardItems?.first else { return }
            log.debug("可用类型 \(item.types)")
            for t in item.types {
                if let plist = item.propertyList(forType: t) {
                    log.debug("  [\(t.rawValue)] propertyList = \(plist)")
                } else if let str = item.string(forType: t) {
                    let preview = str.count > 200 ? String(str.prefix(200)) + "..." : str
                    log.debug("  [\(t.rawValue)] string = \(preview)")
                } else if let data = item.data(forType: t) {
                    log.debug("  [\(t.rawValue)] data(\(data.count) bytes)")
                }
            }
        #endif

        PasteDataStore.main.addNewItem(pasteboard)
        changeCount = pasteboard.changeCount

        StatusBarController.shared.triggerPulseAnimation()
        SoundManager.shared.play(.copy)
    }

    /// 检查敏感内容和瞬时内容
    private func shouldIgnoreContent(
        types: [NSPasteboard.PasteboardType],
        checkSensitive: Bool,
        checkEphemeral: Bool
    ) -> String? {
        for type in types {
            let rawType = type.rawValue
            if checkSensitive, Self.sensitiveTypes.contains(rawType) {
                return "机密内容: \(rawType)"
            }
            if checkEphemeral, Self.ephemeralTypes.contains(rawType) {
                return "瞬时内容: \(rawType)"
            }
        }
        return nil
    }

    private func getSourceApplication() -> NSRunningApplication? {
        NSWorkspace.shared.frontmostApplication
    }

    /// 将多个项目合并写入系统剪贴板
    /// 文本类型会用换行符拼接，文件类型会合并 URL，其他类型只写入第一个
    func pasteMultipleData(_ items: [PasteboardModel], _ isAttribute: Bool = true) {
        guard !items.isEmpty else { return }

        for item in items {
            item.updateDate()
            if let itemId = item.id {
                PasteDataStore.main.updateDbItem(id: itemId, item: item)
            }
        }

        pasteModel = items[0]
        NSPasteboard.general.clearContents()

        let success = writeMultipleToPasteboard(items, isAttribute: isAttribute)
        guard success else { return }

        PasteDataStore.main.moveItemsToFirst(items)
        SoundManager.shared.play(.paste)
    }

    /// 将多个项目合并写入剪贴板
    private func writeMultipleToPasteboard(
        _ items: [PasteboardModel],
        isAttribute: Bool
    ) -> Bool {
        let shouldPasteAsPlainText = !isAttribute || PasteUserDefaults.pasteOnlyText

        let textItems = items.filter { $0.pasteboardType.isText() }
        let fileItems = items.filter { $0.type == .file }
        let imageItems = items.filter { $0.pasteboardType.isImage() }

        // 文件类型
        if !fileItems.isEmpty {
            return writeMultipleFileURLs(fileItems)
        }

        // 图片类型
        if !imageItems.isEmpty {
            return writeMultipleImages(imageItems)
        }

        // 文本类型合并
        if !textItems.isEmpty {
            if shouldPasteAsPlainText {
                return writeMultiplePlainText(textItems)
            } else {
                return writeMultipleRichText(textItems)
            }
        }

        return false
    }

    /// 合并多个纯文本
    private func writeMultiplePlainText(_ items: [PasteboardModel]) -> Bool {
        let texts = items.compactMap { item -> String? in
            var text = item.searchText
            if PasteUserDefaults.removeTailingNewline {
                text = text.trimmingTrailingNewlines()
            }
            return text.isEmpty ? nil : text
        }
        guard !texts.isEmpty else { return false }

        let combined = texts.joined(separator: "\n")
        NSPasteboard.general.setString(combined, forType: .string)
        return true
    }

    /// 合并多个富文本
    private func writeMultipleRichText(_ items: [PasteboardModel]) -> Bool {
        let combined = NSMutableAttributedString()
        let newline = NSAttributedString(string: "\n")

        for (index, item) in items.enumerated() {
            if let attr = NSAttributedString(with: item.data, type: item.pasteboardType) {
                let mutable = NSMutableAttributedString(attributedString: attr)
                if PasteUserDefaults.removeTailingNewline {
                    mutable.trimTrailingNewlines()
                }
                combined.append(mutable)
                if index < items.count - 1 {
                    combined.append(newline)
                }
            } else {
                var text = item.searchText
                if PasteUserDefaults.removeTailingNewline {
                    text = text.trimmingTrailingNewlines()
                }
                combined.append(NSAttributedString(string: text))
                if index < items.count - 1 {
                    combined.append(newline)
                }
            }
        }

        guard combined.length > 0 else { return false }

        let rtfType = items.first?.pasteboardType ?? .rtf
        if let data = combined.toData(with: rtfType) {
            NSPasteboard.general.setData(data, forType: rtfType)
        } else {
            NSPasteboard.general.setString(combined.string, forType: .string)
        }
        return true
    }

    /// 合并多个文件 URL
    private func writeMultipleFileURLs(_ items: [PasteboardModel]) -> Bool {
        let fileManager = FileManager.default
        var allURLs: [URL] = []

        for item in items {
            guard let filePaths = String(data: item.data, encoding: .utf8) else {
                continue
            }
            let urls = filePaths
                .components(separatedBy: "\n")
                .lazy
                .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
                .filter { !$0.isEmpty && fileManager.fileExists(atPath: $0) }
                .map { URL(fileURLWithPath: $0) }
            allURLs.append(contentsOf: urls)
        }

        guard !allURLs.isEmpty else { return false }
        pasteboard.writeObjects(allURLs as [NSPasteboardWriting])
        return true
    }

    /// 多张图片写入剪贴板：先写为临时文件，再以文件 URL 方式写入（确保目标应用能接收全部图片）
    private func writeMultipleImages(_ items: [PasteboardModel]) -> Bool {
        let tempDir = FileManager.default.temporaryDirectory
            .appending(path: "ClipboardPaste")

        // 清理旧的临时目录
        try? FileManager.default.removeItem(at: tempDir)
        try? FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)

        var fileURLs: [URL] = []
        for (index, item) in items.enumerated() {
            let ext = item.pasteboardType == .png ? "png" : "tiff"
            let fileName = "image_\(index + 1).\(ext)"
            let fileURL = tempDir.appending(path: fileName)
            do {
                try item.data.write(to: fileURL)
                fileURLs.append(fileURL)
            } catch {
                log.error("写入临时图片文件失败: \(error)")
            }
        }

        guard !fileURLs.isEmpty else { return false }
        pasteboard.writeObjects(fileURLs as [NSPasteboardWriting])

        // 粘贴完成后延迟清理临时文件，给目标应用足够时间读取
        let cleanupDir = tempDir
        Task.detached {
            try? await Task.sleep(for: .seconds(10))
            try? FileManager.default.removeItem(at: cleanupDir)
        }

        return true
    }

    /// 将数据写入系统剪贴板
    /// - Returns: 是否成功写入
    private func writeToPasteboard(_ data: PasteboardModel, isAttribute: Bool) -> Bool {
        let shouldPasteAsPlainText = !isAttribute || PasteUserDefaults.pasteOnlyText

        if data.pasteboardType.isText(), shouldPasteAsPlainText {
            writePlainText(data)
            return true
        }
        if data.type == .file {
            return writeFileURLs(data)
        }
        writeRawData(data)
        return true
    }

    /// 写入纯文本
    private func writePlainText(_ data: PasteboardModel) {
        var text = data.searchText
        if PasteUserDefaults.removeTailingNewline {
            text = text.trimmingTrailingNewlines()
        }
        NSPasteboard.general.setString(text, forType: .string)
    }

    /// 写入文件 URL
    /// - Returns: 是否有有效文件写入
    private func writeFileURLs(_ data: PasteboardModel) -> Bool {
        guard let filePaths = String(data: data.data, encoding: .utf8) else {
            return false
        }

        let fileManager = FileManager.default
        let validURLs = filePaths
            .components(separatedBy: "\n")
            .lazy
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty && fileManager.fileExists(atPath: $0) }
            .map { URL(fileURLWithPath: $0) }

        let urlArray = Array(validURLs)
        guard !urlArray.isEmpty else { return false }

        pasteboard.writeObjects(urlArray as [NSPasteboardWriting])
        return true
    }

    /// 写入原始数据（富文本、图片等）
    private func writeRawData(_ data: PasteboardModel) {
        // 处理需要去除末尾换行的富文本
        if data.pasteboardType.isText(),
           PasteUserDefaults.removeTailingNewline,
           let attributedString = NSAttributedString(with: data.data, type: data.pasteboardType)
        {
            let mutableString = NSMutableAttributedString(attributedString: attributedString)
            mutableString.trimTrailingNewlines()

            if let processedData = mutableString.toData(with: data.pasteboardType) {
                NSPasteboard.general.setData(processedData, forType: data.pasteboardType)
                return
            }
        }

        NSPasteboard.general.setData(data.data, forType: data.pasteboardType)
    }
}

// MARK: - NSMutableAttributedString Extension

extension NSMutableAttributedString {
    func trimTrailingNewlines() {
        var currentLength = length
        while currentLength > 0 {
            let lastCharRange = NSRange(location: currentLength - 1, length: 1)
            let lastChar = attributedSubstring(from: lastCharRange).string

            if lastChar == "\n" || lastChar == "\r" {
                currentLength -= 1
            } else {
                break
            }
        }

        if currentLength < length {
            deleteCharacters(in: NSRange(location: currentLength, length: length - currentLength))
        }
    }
}

// MARK: - Notification

extension Notification.Name {
    static let pasteboardPauseStateChanged = Notification.Name("pasteboardPauseStateChanged")
}
