//
//  PasteBoard.swift
//  Clipboard
//
//  Created by crown on 2025/9/13.
//

import AppKit
import Combine
import Foundation

final class PasteBoard {
    static let main = PasteBoard()

    let pasteboard = NSPasteboard.general
    private let timerInterval = 0.5
    var changeCount: Int
    var pasteModel: PasteboardModel?
    private var timer: Timer?

    // MARK: - 暂停功能

    @Published private(set) var isPaused: Bool = false
    private(set) var pausedAt: Date?
    /// 暂停持续时长（秒），nil 表示无限期
    private var pauseDuration: TimeInterval?
    private var resumeTimer: Timer?

    private static let sensitiveTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "com.apple.password",
        "com.apple.securetext",
        "com.agilebits.onepassword", // 1Password
        "com.lastpass.mac", // LastPass
        "com.dashlane.dashlanephonefinal", // Dashlane
        "com.keeper.KeeperPassManager", // Keeper
        "io.enpass.Enpass", // Enpass
        "com.bitwarden.desktop" // Bitwarden
    ]

    private static let ephemeralTypes: Set<String> = [
        "org.nspasteboard.TransientType", // 瞬时内容标准标识
        "org.nspasteboard.AutoGeneratedType", // 自动生成内容
        "org.nspasteboard.RestoredType", // 恢复的内容
        "de.petermaurer.TransientPasteboardType", // TextExpander/Butler
        "com.typeit4me.clipping", // TypeIt4Me
        "com.apple.pasteboard.promised-file-content-type"
    ]

    init() {
        changeCount = pasteboard.changeCount
    }

    func startListening() {
        stopListening()

        timer = Timer.scheduledTimer(
            timeInterval: timerInterval,
            target: self,
            selector: #selector(checkForChangesInPasteboard),
            userInfo: nil,
            repeats: true
        )
        RunLoop.main.add(timer!, forMode: .common)
    }

    func stopListening() {
        timer?.invalidate()
        timer = nil
    }

    // MARK: - 暂停/恢复

    /// - Parameter duration: 暂停时长（秒），nil 表示无限期暂停
    func pause(for duration: TimeInterval? = nil) {
        if isPaused {
            resumeTimer?.invalidate()
            resumeTimer = nil
        } else {
            stopListening()
        }

        isPaused = true
        pausedAt = Date()
        pauseDuration = duration

        if let duration {
            resumeTimer = Timer.scheduledTimer(
                withTimeInterval: duration,
                repeats: false
            ) { [weak self] _ in
                Task { @MainActor in
                    self?.resume()
                }
            }
            RunLoop.main.add(resumeTimer!, forMode: .common)
        }
    }

    func resume() {
        guard isPaused else { return }

        resumeTimer?.invalidate()
        resumeTimer = nil

        isPaused = false
        pausedAt = nil
        pauseDuration = nil
        startListening()
    }

    var pauseEndTime: Date? {
        guard isPaused, let pausedAt, let pauseDuration else {
            return nil
        }
        return pausedAt.addingTimeInterval(pauseDuration)
    }

    /// 是否为无限期暂停
    var isIndefinitePause: Bool {
        isPaused && pauseDuration == nil
    }

    @objc private func checkForChangesInPasteboard() {
        guard pasteboard.changeCount != changeCount else {
            return
        }

        if pasteModel != nil {
            changeCount = pasteboard.changeCount
            pasteModel = nil
            return
        }

        let types = pasteboard.types ?? []

        // 检查隐私设置：忽略机密内容和瞬时内容
        let checkSensitive = PasteUserDefaults.ignoreSensitiveContent
        let checkEphemeral = PasteUserDefaults.ignoreEphemeralContent

        if checkSensitive || checkEphemeral {
            let ignoreResult = shouldIgnoreContent(
                types: types,
                checkSensitive: checkSensitive,
                checkEphemeral: checkEphemeral
            )
            if let reason = ignoreResult {
                log.info("检测到需忽略的内容，跳过记录: \(reason)")
                changeCount = pasteboard.changeCount
                return
            }
        }

        // 检查隐私设置：忽略特定应用
        let ignoredApps = PasteUserDefaults.ignoredApps
        if !ignoredApps.isEmpty, let sourceApp = getSourceApplication() {
            let shouldIgnore = ignoredApps.contains { app in
                if let bundleId = app.bundleIdentifier,
                   bundleId == sourceApp.bundleIdentifier {
                    return true
                }
                return app.path == sourceApp.bundleURL?.path
            }

            if shouldIgnore {
                log.info(
                    "来自忽略应用的内容，跳过记录: \(sourceApp.localizedName ?? "Unknown")"
                )
                changeCount = pasteboard.changeCount
                return
            }
        }

        #if DEBUG
            guard let item = pasteboard.pasteboardItems?.first else { return }
            logPasteboardItem(item)
        #endif

        PasteDataStore.main.addNewItem(pasteboard)
        changeCount = pasteboard.changeCount

        StatusBarController.shared.triggerPulseAnimation()
        SoundManager.shared.play(.copy)
    }

    #if DEBUG
    private func logPasteboardItem(_ item: NSPasteboardItem) {
    log.debug("可用类型 \(item.types)")
    for type in item.types {
        if let data = item.data(forType: type), data.count > 4096 {
            log.debug("  [\(type.rawValue)] data(\(data.count) bytes)")
        } else if let plist = item.propertyList(forType: type) {
            log.debug("  [\(type.rawValue)] propertyList = \(plist)")
        } else if let str = item.string(forType: type) {
            let preview =
                str.prefix(201).count > 200 ? String(str.prefix(200)) + "..." : str
            log.debug("  [\(type.rawValue)] string = \(preview)")
        } else if let data = item.data(forType: type) {
            log.debug("  [\(type.rawValue)] data(\(data.count) bytes)")
        }
    }
    }
    #endif

    /// 检查敏感内容和瞬时内容
    private func shouldIgnoreContent(
        types: [NSPasteboard.PasteboardType],
        checkSensitive: Bool,
        checkEphemeral: Bool
    ) -> String? {
        for type in types {
            let rawType = type.rawValue
            if checkSensitive, Self.sensitiveTypes.contains(rawType) {
                return "机密内容: \(rawType)"
            }
            if checkEphemeral, Self.ephemeralTypes.contains(rawType) {
                return "瞬时内容: \(rawType)"
            }
        }
        return nil
    }

    private func getSourceApplication() -> NSRunningApplication? {
        NSWorkspace.shared.frontmostApplication
    }

}
